# Generated by Django 4.1.5 on 2023-01-30 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('bookType', models.CharField(choices=[('Other', 'OTHER'), ('Food', 'FOOD'), ('Apparel', 'APPAREL'), ('Tech', 'TECH')], default='Other', max_length=30)),
                ('description', models.TextField(default="User hasn't described the product yet.", max_length=300)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, default='defaultPicture.png', null=True, upload_to='products_images')),
                ('averageRating', models.FloatField(default=0)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.products')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
