# Generated by Django 4.1.5 on 2023-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default="User hasn't described the product yet.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='productType',
            field=models.CharField(choices=[('OTHER', 'Other'), ('FOOD', 'Food'), ('APPAREL', 'Apparel'), ('OUTDOORS', 'Outdoors'), ('TECH', 'Tech')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
