# Generated by Django 4.1.5 on 2023-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='defaultProductImage.png', null=True, upload_to='products_images'),
        ),
    ]
