# Generated by Django 4.1.5 on 2023-02-02 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabilty',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='Available', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='wishlisted',
            field=models.ManyToManyField(related_name='wishlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
