# Generated by Django 4.1.5 on 2023-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_product_wishlisted_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_product',
            field=models.ManyToManyField(to='market.product'),
        ),
    ]
