# Generated by Django 4.1.5 on 2023-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
