# Generated by Django 4.1.5 on 2023-02-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_alter_product_price_alter_product_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_cart',
        ),
    ]
