# Generated by Django 4.1.5 on 2023-02-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_remove_product_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availabilty',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('Other', 'Other'), ('Food', 'Food'), ('Apparel', 'Apparel'), ('Outdoors', 'Outdoors'), ('Tech', 'Tech'), ('Memes', 'Memes')], default='Other', max_length=30),
        ),
    ]
