# Generated by Django 4.1.5 on 2023-03-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_product_availabilty_alter_product_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabilty',
            new_name='availability',
        ),
    ]
