# Generated by Django 4.1.5 on 2023-03-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_rename_availabilty_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='media/defaultProductImage.png', null=True, upload_to='products_images'),
        ),
    ]
