# Generated by Django 4.1.5 on 2023-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='defaultProductImage.png', null=True, upload_to='products_images'),
        ),
    ]
