# Generated by Django 4.1.5 on 2023-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default="User hasn't described the product yet.", max_length=1000, null=True),
        ),
    ]
