# Generated by Django 4.1.5 on 2023-03-09 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0007_remove_cart_quantity_remove_cart_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_identifier', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0.0, null=True)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('transction_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transction_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
            options={
                'ordering': ['checkout_date'],
            },
        ),
    ]
