# Generated by Django 4.1.5 on 2023-03-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transction_buyer',
            new_name='transaction_buyer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transction_item',
            new_name='transaction_item',
        ),
    ]
