# Generated by Django 4.1.5 on 2023-03-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_quantity_remove_cart_total_price_and_more'),
        ('transaction', '0002_rename_transction_buyer_transaction_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_quantity', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_item', to='cart.cart'),
        ),
    ]
