# Generated by Django 4.1.5 on 2023-03-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
