# Generated by Django 4.1.5 on 2023-02-06 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='seller',
            new_name='buyer',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_cart',
            field=models.ManyToManyField(blank=True, related_name='users_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
