# Generated by Django 4.1.5 on 2023-02-06 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_rename_seller_cart_buyer_cart_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_cart',
            field=models.ManyToManyField(blank=True, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
