# Generated by Django 4.1.5 on 2023-02-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_cart',
        ),
    ]
