# Generated by Django 4.1.5 on 2023-02-09 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_remove_cart_totalprice_remove_cart_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='buyer',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_cart',
            field=models.ManyToManyField(blank=True, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
