# Generated by Django 4.1.5 on 2023-03-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_quantity_remove_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
